### ISSUE TITLE
Fork or clone scoop

### ISSUE THREAD

**Issue by r15ch13** [scoopinstaller/scoop-main#1]
@h404bi I think it would be better to clone or fork scoops main bucket to keep the commit history and then remove the code.

_Sent from my OnePlus5T using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by h404bi** [comment]
You're right, I'll rebase the branch.

**Comment by h404bi** [comment]
I have used the method provided by @Ash258 , `git filter-branch --prune-empty --subdirectory-filter bucket` to rebase the branch.

There is a question, about the bucket name. I prefer `core` over `main`, refer to `Homebrew/homebrew-core` as reference.

**Comment by Ash258** [comment]
I prefer `main`. It is used in wiki, code, everywhere. Users are familiar with it.

**Comment by h404bi** [comment]
Just changed to `scoop-main`, I wonder when r15ch13 will have time to pause the update automation. No way to split the main bucket if the automation is still working.

**Comment by r15ch13** [comment]
Stopping the update service is no big deal.

**Comment by r15ch13** [comment]
Is it possible to coordinate this via discord today? :smile:

**Comment by abstiger** [comment]
while `scoop update` with default git config, it failed with:
> RPC failed; curl 18 transfer closed with outstanding read data remaining

while `git config --global http.postBuffer 524288000`
> RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errfno 10054

then `git config --global http.postbuffer 20485760000`
it finally succeed!  

is it related to the commit history?
