### ISSUE TITLE
openssh@7.6p1: hash check failed

### ISSUE THREAD

**Issue by OhYee** [scoopinstaller/scoop-main#26]
Installing 'openssh' (7.6p1) [64bit]
Loading gcc-libs-6.4.0-1-x86_64.pkg.tar.xz from cache
Checking hash of gcc-libs-6.4.0-1-x86_64.pkg.tar.xz ... ok.
Loading heimdal-1.5.3-9-x86_64.pkg.tar.xz from cache
Checking hash of heimdal-1.5.3-9-x86_64.pkg.tar.xz ... ok.
Loading heimdal-libs-1.5.3-9-x86_64.pkg.tar.xz from cache
Checking hash of heimdal-libs-1.5.3-9-x86_64.pkg.tar.xz ... ok.
icu-59.1-1-x86_64.pkg.tar.xz (7.3 MB) [=================================================>                                                                                                      ]  33%
Checking hash of icu-59.1-1-x86_64.pkg.tar.xz ... ERROR Hash check failed!
App:         main/openssh
URL:         http://repo.msys2.org/msys/x86_64/icu-59.1-1-x86_64.pkg.tar.xz
First bytes: FD 37 7A 58 5A 00 00 04
Expected:    d64bbf81b569b322f428cc4a18071991abca4b0d56c2ec2ce74052348d2b2e7a
Actual:      dc32ed0db81b7eda6a5b4f1e58e55974fab09e1b254c2e8f28496da0a727865e

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/scoopinstaller/scoop-main/issues/new?title=openssh%407.6p1%3a+hash+check+failed

**Comment by Ash258** [comment]
> => ] 33%

`scoop uninstall openssh; scoop install openssh` `scoop cache rm openssh` optionally

**Comment by OhYee** [comment]
Thanks. It works.
