### ISSUE TITLE
Application for scoopinstaller's reviewer

### ISSUE THREAD

**Issue by niheaven** [scoopinstaller/scoop-main#8]
Since now this repo is protected, and PRs require a approving review by reviewers with write access, could I join the team as a reviewer?

**Comment by h404bi** [comment]
Approve, you may contact r15ch13.

**Comment by niheaven** [comment]
@r15ch13 If approved, I'll do my best. Thanks.

**Comment by r15ch13** [comment]
@niheaven invite to @scoopinstaller has been send :)

**Comment by niheaven** [comment]
Thanks!
